enum QuestionActionType {
    CREATE_QUESTION = "CREATE_QUESTION",
    DESCRIBE_QUESTIONS = "DESCRIBE_QUESTIONS",
    EDIT_QUESTION = "EDIT_QUESTION",
    GET_QUESTIONS_FOR_READABLE ="GET_QUESTIONS_FOR_READABLE"
}

export default QuestionActionType;