export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const DESCRIBE_QUESTIONS = "DESCRIBE_QUESTIONS";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const GET_QUESTIONS_FOR_READABLE ="GET_QUESTIONS_FOR_READABLE";

export const CREATE_READABLE = "CREATE_READABLE";
export const DESCRIBE_READABLES = "DESCRIBE_READABLES";
export const GET_READABLE = "GET_READABLE";
export const EDIT_READABLE = "EDIT_READABLE";
